# Version 0.0.1
From ubuntu:14.04
MAINTAINER Gao Xiong "growdane@gmail.com"
RUN apt-get update
RUN apt-get install -y nginx
RUN echo "Hi, I an in your container" > /usr/share/nginx/html/index.html

EXPOSE 80
